version: '3'

services:
  nginx:
    container_name: 'srv1'
    restart: always
    image: nginx:latest
    expose:
      - 80
    ports: 
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app/acts/static:/srv/www/acts/static
      - ./logs:/srv/www/logs # удаляется папка в контейнере и заменяется на папку их хоста
    depends_on: 
      - web
  db:
    image: postgres
    container_name: 'db1'
    environment:
      POSTGRES_PASSWORD: pww2
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: ../../docker_entrypoint.sh
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'app1'
    restart: always
    volumes:
      - .:/code
    expose: 
       - "8000"
    ports:
       - "8000:8000"
    depends_on:
      - db
