version: '3'

services:
  web:
    build: .
    command: ../../acthiddeen_init.sh
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'app1'
    restart: always
    volumes:
      - .:/code
      - /srv/www/acts/static:/code/app/acts/static
    expose: 
       - "8000"
    ports:
       - "8000:8000"
    networks:
      KRNet:
        ipv4_address: 172.16.1.3

networks:
  KRNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

