version: '3'

services:
  nginx:
    container_name: 'srv1'
    restart: always
    image: nginx:latest
    expose:
      - "8000"
    ports: 
      - 8055:8055
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app/acts/static:/srv/www/acts/static
      - ./logs:/srv/www/logs # удаляется папка в контейнере и заменяется на папку их хоста

  web:
    build: .
    command: ../../acthiddeen_init.sh
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'app1'
    restart: always
    volumes:
      - .:/code
    expose: 
       - "8000"
    ports:
       - "8000:8000"
