# Generated by Django 5.1.4 on 2025-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateField(verbose_name='Дата заключения')),
                ('customer', models.CharField(blank=True, max_length=50, verbose_name='Заказчик')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Номер акта')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('hvs_probe_number', models.CharField(blank=True, max_length=50, verbose_name='Номер пробы ХВС')),
                ('gvs_probe_number', models.CharField(blank=True, max_length=50, verbose_name='Номер пробы ГВС')),
                ('probe_date', models.DateField(verbose_name='Дата отбора проб')),
                ('chemistry_number', models.CharField(blank=True, max_length=20, verbose_name='Номер протокола химии')),
                ('chemistry_date', models.DateField(verbose_name='Дата протокола химии')),
                ('chemistry_order_number', models.CharField(blank=True, max_length=20, verbose_name='Номер заявки на химию')),
                ('chemistry_order_date', models.DateField(verbose_name='Дата заявки на химию')),
                ('bio_number', models.CharField(blank=True, max_length=20, verbose_name='Номер протокола био')),
                ('bio_date', models.DateField(verbose_name='Дата протокола био')),
                ('hvs_bio_code', models.CharField(blank=True, max_length=20, verbose_name='Ко пробы ХВС')),
                ('gvs_bio_code', models.CharField(blank=True, max_length=20, verbose_name='Ко пробы ГВС')),
                ('hvs_bio_referral', models.CharField(blank=True, max_length=20, verbose_name='Направление ХВС био')),
                ('gvs_bio_referral', models.CharField(blank=True, max_length=20, verbose_name='Направление ГВС био')),
                ('bio_begin_date', models.DateField(verbose_name='Дата начала испытаний')),
                ('bio_end_date', models.DateField(verbose_name='Дата конца испытаний')),
            ],
            options={
                'verbose_name': 'Анализ воды',
                'verbose_name_plural': 'Анализы воды',
            },
        ),
    ]
