# Generated by Django 5.1.4 on 2025-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterassay',
            options={'ordering': ['-id'], 'verbose_name': 'Анализ воды', 'verbose_name_plural': 'Анализы воды'},
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='act_date',
            field=models.DateField(null=True, verbose_name='Дата акта'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_begin_date',
            field=models.DateField(null=True, verbose_name='Дата начала испытаний'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_date',
            field=models.DateField(null=True, verbose_name='Дата протокола био'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_end_date',
            field=models.DateField(null=True, verbose_name='Дата конца испытаний'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='chemistry_date',
            field=models.DateField(null=True, verbose_name='Дата протокола химии'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='chemistry_order_date',
            field=models.DateField(null=True, verbose_name='Дата заявки на химию'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='conclusion_date',
            field=models.DateField(null=True, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='gvs_bio_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код пробы ГВС'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='hvs_bio_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код пробы ХВС'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='probe_date',
            field=models.DateField(null=True, verbose_name='Дата отбора проб'),
        ),
    ]
