# Generated by Django 5.1.4 on 2025-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_waterassay_options_alter_waterassay_act_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterassay',
            name='chroma',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цветность'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='fe',
            field=models.CharField(blank=True, max_length=20, verbose_name='fe'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='ox',
            field=models.CharField(blank=True, max_length=20, verbose_name='Окисляемость'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='ph',
            field=models.CharField(blank=True, max_length=20, verbose_name='ph'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='rig',
            field=models.CharField(blank=True, max_length=20, verbose_name='Жесткость'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='turb',
            field=models.CharField(blank=True, max_length=20, verbose_name='Мутность'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='act_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала испытаний'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата протокола био'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='bio_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца испытаний'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='chemistry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата протокола химии'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='chemistry_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки на химию'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='waterassay',
            name='probe_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отбора проб'),
        ),
    ]
