# Generated by Django 5.1.4 on 2025-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_waterassay_chroma_waterassay_fe_waterassay_ox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterassay',
            name='chroma',
        ),
        migrations.RemoveField(
            model_name='waterassay',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='waterassay',
            name='ox',
        ),
        migrations.RemoveField(
            model_name='waterassay',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='waterassay',
            name='rig',
        ),
        migrations.RemoveField(
            model_name='waterassay',
            name='turb',
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_chroma',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС Цветн.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_fe',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС fe'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_ox',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС Окисл.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_ph',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС ph'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_rig',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС Жестк.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='gvs_turb',
            field=models.CharField(blank=True, max_length=20, verbose_name='ГВС Мутн.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_chroma',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС Цветн.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_fe',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС fe'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_ox',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС Окисл.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_ph',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС ph'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_rig',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС Жестк.'),
        ),
        migrations.AddField(
            model_name='waterassay',
            name='hvs_turb',
            field=models.CharField(blank=True, max_length=20, verbose_name='ХВС Мутн.'),
        ),
    ]
