# Generated by Django 2.1.7 on 2019-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks14base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommon',
            name='district_genitive',
            field=models.CharField(default=' ', max_length=30, verbose_name='Район (род падеж)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectcommon',
            name='district_prepositional',
            field=models.CharField(max_length=30, verbose_name='Район (предл падеж)'),
        ),
    ]
