# Generated by Django 2.1.7 on 2019-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks14base', '0002_auto_20190406_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_genitive', models.CharField(max_length=100, verbose_name='система (род падеж)')),
                ('act_number', models.CharField(max_length=1, verbose_name='Номер Акта')),
                ('begin_contract_date', models.CharField(max_length=20, verbose_name='Начало по контракту')),
                ('end_contract_date', models.CharField(max_length=20, verbose_name='Конец по контракту')),
                ('begin_fact_date', models.CharField(max_length=20, verbose_name='Начало по факту')),
                ('act_date', models.CharField(max_length=20, verbose_name='Дата Акта')),
                ('summa', models.CharField(max_length=20, verbose_name='Сумма контракта')),
                ('volume', models.CharField(max_length=30, verbose_name='Объем с ед изм')),
                ('telephonogramm_date', models.CharField(max_length=20, verbose_name='Дата телефонограммы')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('district_prepositional', models.CharField(max_length=20, verbose_name='Район (предл падеж)')),
                ('contract_number', models.CharField(max_length=40, verbose_name='№ Контракта')),
                ('contract_date', models.CharField(max_length=20, verbose_name='Дата контракта')),
                ('contractor', models.CharField(max_length=20, verbose_name='Подрядчик без кавычек')),
                ('contractor_address', models.CharField(max_length=100, verbose_name='Адрес подрядчика')),
                ('contractor_OKPO', models.CharField(max_length=8, verbose_name='ОКПО подрядчика')),
                ('contractor_delegate', models.CharField(max_length=20, verbose_name='Предст. подр.')),
                ('contractor_delegate_genitive', models.CharField(max_length=50, verbose_name='Предст. подр.(род падеж)')),
                ('UK_full', models.CharField(max_length=120, verbose_name='УК полное')),
                ('UK_delegate', models.CharField(max_length=20, verbose_name='Предст. УК')),
                ('UK_delegate_genitive', models.CharField(max_length=50, verbose_name='Предст. УК (род падеж)')),
                ('UK_position_genitive', models.CharField(max_length=30, verbose_name='Должность Предст. УК (род падеж)')),
                ('UK_decree_genitive', models.CharField(max_length=100, verbose_name='Основание УК (род падеж)')),
                ('supervisor_OSK_number', models.CharField(max_length=2, verbose_name='инженера ОСК№')),
                ('supervisor_delegate', models.CharField(max_length=20, verbose_name='Представитель Заказчика')),
                ('supervisor_delegate_genitive', models.CharField(max_length=50, verbose_name='Представитель заказчика (род падеж)')),
                ('supervisor_decree_genitive', models.CharField(max_length=40, verbose_name='Основание заказчика (род падеж')),
                ('supervisor_decree_dative', models.CharField(max_length=40, verbose_name='Основание заказчика (дательн падеж')),
                ('administration_order', models.CharField(blank=True, max_length=100, verbose_name='по распоряжению администр.')),
                ('owner_delegate_position', models.CharField(blank=True, max_length=150, verbose_name='Должность предст. собственника')),
                ('owner_delegate', models.CharField(blank=True, max_length=30, verbose_name='Представитель Собственника')),
                ('owner_delegate_genitive', models.CharField(blank=True, max_length=30, verbose_name='Предст. Собственника (род падеж)')),
                ('owner_delegate_decree', models.CharField(blank=True, max_length=100, verbose_name='Основание предст. собств.')),
                ('owner_delegate_decree_genitive', models.CharField(blank=True, max_length=100, verbose_name='Основание предст. собств. (род. падеж)')),
                ('administration_delegate_position', models.CharField(max_length=50, verbose_name='Должн. предст. адм.')),
                ('administration_delegate_decree', models.CharField(max_length=50, verbose_name='Основание предст. адм.')),
                ('administration_delegate', models.CharField(max_length=20, verbose_name='Предст. Адм.')),
                ('acts', models.ManyToManyField(blank=True, related_name='object_common', to='ks14base.ActSpecific')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ks14act',
            options={'verbose_name': 'Финдоки ', 'verbose_name_plural': 'Финдоки'},
        ),
        migrations.AlterField(
            model_name='ks14act',
            name='system_genitive',
            field=models.CharField(max_length=100, verbose_name='система (род падеж)'),
        ),
    ]
