# Generated by Django 2.1.7 on 2019-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks14base', '0003_auto_20190411_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actspecific',
            options={'verbose_name': 'Информация акта ', 'verbose_name_plural': 'Информация акта '},
        ),
        migrations.AlterModelOptions(
            name='objectcommon',
            options={'verbose_name': 'Информация объекта ', 'verbose_name_plural': 'Информация объекта '},
        ),
        migrations.AlterField(
            model_name='ks14act',
            name='UK_position_genitive',
            field=models.CharField(max_length=100, verbose_name='Должность Предст. УК (род падеж)'),
        ),
        migrations.AlterField(
            model_name='ks14act',
            name='administration_delegate_position',
            field=models.CharField(max_length=150, verbose_name='Должн. предст. адм.'),
        ),
        migrations.AlterField(
            model_name='objectcommon',
            name='UK_position_genitive',
            field=models.CharField(max_length=100, verbose_name='Должность Предст. УК (род падеж)'),
        ),
        migrations.AlterField(
            model_name='objectcommon',
            name='administration_delegate_position',
            field=models.CharField(max_length=150, verbose_name='Должн. предст. адм.'),
        ),
    ]
