# Generated by Django 2.1.7 on 2020-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacts',
            name='acts_instance_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кол-во экземпдяров'),
        ),
        migrations.AlterField(
            model_name='blowdownact',
            name='purge_method',
            field=models.CharField(default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=500, verbose_name='Метод продувки'),
        ),
        migrations.AlterField(
            model_name='blowdownact',
            name='trassa',
            field=models.CharField(default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=500, verbose_name='Трасса'),
        ),
        migrations.AlterField(
            model_name='blowdownact',
            name='trassa_lenght',
            field=models.CharField(max_length=50, verbose_name='Длина трассы'),
        ),
        migrations.AlterField(
            model_name='hiddenactis',
            name='materials',
            field=models.CharField(max_length=500, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='hiddenactis',
            name='permitted_work',
            field=models.CharField(max_length=500, verbose_name='Разрешено'),
        ),
        migrations.AlterField(
            model_name='hiddenactis',
            name='presented_work',
            field=models.CharField(max_length=500, verbose_name='Предъявл.'),
        ),
        migrations.AlterField(
            model_name='hiddenactis',
            name='work_SNIP',
            field=models.CharField(blank=True, max_length=500, verbose_name='СНИП:'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='contractor',
            field=models.CharField(default='Общество с ограниченной ответственностью «Интера».', max_length=500, verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='contractor_engineer',
            field=models.CharField(max_length=200, verbose_name='Прораб'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='contractor_engineer_decree',
            field=models.CharField(max_length=200, verbose_name='Приказ прораба'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='contractor_requisite',
            field=models.CharField(default='Свидетельство о государственной регистрации серия 78№007274277 от  02.09.2009, ОГРН 1097847236783, ИНН 7805498649, 198188, г. Санкт-Петербург, ул. Возрождения, д.20, литер А, тел. 242-78-10.', max_length=500, verbose_name='Реквизиты подрядчика'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='designer',
            field=models.CharField(max_length=500, verbose_name='Проектант'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='designer_engineer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Проектировщик'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='designer_engineer_decree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Приказ проектировщика'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='exec_documents',
            field=models.CharField(max_length=500, verbose_name='Исполн.'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='supervisor_engineer',
            field=models.CharField(max_length=200, verbose_name='Технадзор'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='supervisor_engineer_decree',
            field=models.CharField(max_length=200, verbose_name='Приказ технадзора'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='system_type',
            field=models.CharField(max_length=500, verbose_name='тип'),
        ),
    ]
