# Generated by Django 4.0.5 on 2022-07-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0005_auto_20220521_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectacts',
            name='contractor_supervisor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Технадзор наш'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='contractor_supervisor_decree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Приказ технадз. наш'),
        ),
    ]
