# Generated by Django 4.0.5 on 2022-07-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0006_alter_objectacts_contractor_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingPurgingAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Ном. Акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('trassa', models.CharField(default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=500, verbose_name='Трасса')),
                ('trassa_lenght', models.CharField(max_length=50, verbose_name='Длина трассы')),
                ('purge_method', models.CharField(default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=500, verbose_name='Метод продувки')),
            ],
            options={
                'verbose_name': 'Акт промыки-продувки',
                'verbose_name_plural': 'Акты промыки-продувки',
            },
        ),
        migrations.AlterModelOptions(
            name='hiddenactis',
            options={'ordering': ['act_number'], 'verbose_name': 'Акт скрытых', 'verbose_name_plural': 'Акты скрытых'},
        ),
        migrations.AlterModelOptions(
            name='objectacts',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.RemoveField(
            model_name='objectacts',
            name='blow_down_act',
        ),
        migrations.AlterField(
            model_name='hiddenactis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BlowDownAct',
        ),
        migrations.AddField(
            model_name='objectacts',
            name='washing_purging_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiddenactsbase.washingpurgingact'),
        ),
    ]
