# Generated by Django 4.0.5 on 2022-07-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0007_washingpurgingact_alter_hiddenactis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectacts',
            name='washing_purging_act',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiddenactsbase.washingpurgingact'),
        ),
        migrations.AlterField(
            model_name='washingpurgingact',
            name='act_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата Акта'),
        ),
        migrations.AlterField(
            model_name='washingpurgingact',
            name='act_number',
            field=models.CharField(max_length=20, verbose_name='Ном. Акта'),
        ),
        migrations.AlterField(
            model_name='washingpurgingact',
            name='purge_method',
            field=models.CharField(blank=True, default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=500, verbose_name='Метод продувки'),
        ),
        migrations.AlterField(
            model_name='washingpurgingact',
            name='trassa',
            field=models.CharField(blank=True, default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=500, verbose_name='Трасса'),
        ),
        migrations.AlterField(
            model_name='washingpurgingact',
            name='trassa_lenght',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длина трассы'),
        ),
    ]
