# Generated by Django 4.0.5 on 2022-07-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0008_alter_objectacts_washing_purging_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectacts',
            name='washing_purging_act',
        ),
        migrations.DeleteModel(
            name='WashingPurgingAct',
        ),
    ]
