# Generated by Django 4.0.6 on 2023-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0013_certificate_hiddenactis_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacts',
            name='service_engineer',
            field=models.CharField(blank=True, max_length=200, verbose_name='От УК'),
        ),
    ]
