# Generated by Django 4.0.6 on 2024-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0015_alter_certificate_options_objectacts_a_act_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectacts',
            name='a_act_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата'),
        ),
    ]
