# Generated by Django 4.0.6 on 2024-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0016_alter_objectacts_a_act_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenactis',
            name='act_suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Суффикс'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='acts_prefix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Префикс актов'),
        ),
    ]
