# Generated by Django 5.1.4 on 2025-08-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0017_hiddenactis_act_suffix_objectacts_acts_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_requisites',
            field=models.CharField(blank=True, max_length=100, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expired_year',
            field=models.CharField(blank=True, max_length=7, verbose_name='Истекает'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='material_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название для акта'),
        ),
    ]
