# Generated by Django 2.1.7 on 2019-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HASet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('system_type', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=200)),
                ('supervisor_engineer_full', models.CharField(max_length=200)),
                ('contractor_engineer_full', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=100)),
                ('exec_documents', models.CharField(max_length=100)),
                ('supervisor_engineer_short', models.CharField(max_length=100)),
                ('contractor_engineer_short', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HAStandAlone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=20)),
                ('act_date', models.CharField(max_length=50)),
                ('presented_work', models.CharField(max_length=200)),
                ('materials', models.CharField(max_length=200)),
                ('begin_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('permitted_work', models.CharField(max_length=200)),
            ],
        ),
    ]
