# Generated by Django 2.1.7 on 2019-04-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlowDownAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Ном. Акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('trassa', models.CharField(default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=100, verbose_name='Трасса')),
                ('trassa_lenght', models.CharField(max_length=10, verbose_name='Длина трассы')),
                ('purge_method', models.CharField(default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=100, verbose_name='Метод продувки')),
            ],
            options={
                'verbose_name': 'Акт промыки (продувки)',
            },
        ),
        migrations.CreateModel(
            name='HiddenActIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Ном. Акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('presented_work', models.CharField(max_length=200, verbose_name='Предъявл.')),
                ('materials', models.CharField(max_length=200, verbose_name='Материалы')),
                ('permitted_work', models.CharField(max_length=200, verbose_name='Разрешено')),
                ('begin_date', models.CharField(max_length=50, verbose_name='От:')),
                ('end_date', models.CharField(max_length=50, verbose_name='До:')),
            ],
            options={
                'verbose_name': 'Акт скрытых инженерка ',
                'ordering': ['act_number'],
            },
        ),
        migrations.CreateModel(
            name='ObjectActs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('system_type', models.CharField(max_length=100, verbose_name='тип')),
                ('designer', models.CharField(max_length=200, verbose_name='Проектант')),
                ('contractor', models.CharField(default='Общество с ограниченной ответственностью «Интера».', max_length=300, verbose_name='Подрядчик')),
                ('contractor_requisite', models.CharField(default='Свидетельство о государственной регистрации серия 78№007274277 от  02.09.2009, ОГРН 1097847236783, ИНН 7805498649, 198188, г. Санкт-Петербург, ул. Возрождения, д.20, литер А, тел. 242-78-10.', max_length=200, verbose_name='Реквизиты подрядчика')),
                ('supervisor_engineer', models.CharField(max_length=100, verbose_name='Технадзор')),
                ('contractor_engineer', models.CharField(max_length=100, verbose_name='Прораб')),
                ('project_number', models.CharField(max_length=100, verbose_name='Ном. проекта')),
                ('exec_documents', models.CharField(max_length=100, verbose_name='Исполн.')),
                ('supervisor_engineer_decree', models.CharField(max_length=100, verbose_name='Приказ технадзора')),
                ('contractor_engineer_decree', models.CharField(max_length=100, verbose_name='Приказ прораба')),
                ('acts', models.ManyToManyField(blank=True, related_name='object_acts', to='hiddenactsbase.HiddenActIS')),
                ('blow_down_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiddenactsbase.BlowDownAct')),
            ],
            options={
                'verbose_name': 'Набор актов объекта ',
            },
        ),
    ]
