# Generated by Django 2.1.7 on 2019-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenActIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Ном. Акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('presented_work', models.CharField(max_length=200, verbose_name='Предъявл.')),
                ('materials', models.CharField(max_length=200, verbose_name='Материалы')),
                ('permitted_work', models.CharField(max_length=200, verbose_name='Разрешено')),
                ('begin_date', models.CharField(max_length=50, verbose_name='От:')),
                ('end_date', models.CharField(max_length=50, verbose_name='До:')),
            ],
            options={
                'verbose_name': 'Акт скрытых инженерка ',
                'ordering': ['act_number'],
            },
        ),
        migrations.CreateModel(
            name='ObjectActs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('system_type', models.CharField(max_length=100, verbose_name='тип')),
                ('designer', models.CharField(max_length=200, verbose_name='Проектант')),
                ('contractor', models.CharField(default='Общество с ограниченной ответственностью «Интера».Свидетельство о государственной регистрации серия 78№007274277 от  02.09.2009, ОГРН 1097847236783, ИНН 7805498649, 198188, г. Санкт-Петербург, ул. Возрождения, д.20, литер А, тел. 242-78-10.', max_length=300, verbose_name='Подрядчик')),
                ('supervisor_engineer', models.CharField(max_length=100, verbose_name='Технадзор')),
                ('contractor_engineer', models.CharField(max_length=100, verbose_name='Прораб')),
                ('project_number', models.CharField(max_length=100, verbose_name='Ном. проекта')),
                ('exec_documents', models.CharField(max_length=100, verbose_name='Исполн.')),
                ('supervisor_engineer_decree', models.CharField(max_length=100, verbose_name=' ')),
                ('contractor_engineer_decree', models.CharField(max_length=100, verbose_name=' ')),
                ('acts', models.ManyToManyField(blank=True, related_name='object_acts', to='hiddenactsbase.HiddenActIS')),
            ],
            options={
                'verbose_name': 'Набор актов объекта ',
            },
        ),
    ]
