# Generated by Django 2.1.7 on 2019-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0002_auto_20190417_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlowDownAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Ном. Акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('trassa', models.CharField(default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=100, verbose_name='Трасса')),
                ('trassa_lenght', models.CharField(max_length=10, verbose_name='Длина трассы')),
                ('purge_method', models.CharField(default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=100, verbose_name='Метод продувки')),
            ],
            options={
                'verbose_name': 'Акт промыки (продувки)',
            },
        ),
        migrations.AddField(
            model_name='objectacts',
            name='blow_down_act',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='hiddenactsbase.BlowDownAct'),
            preserve_default=False,
        ),
    ]
