# Generated by Django 2.1.7 on 2019-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0003_objectacts_blow_down_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenactis',
            name='work_SNIP',
            field=models.CharField(default=' ', max_length=100, verbose_name='СНИП:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectacts',
            name='designer_engineer',
            field=models.CharField(default=' ', max_length=100, verbose_name='Проектировщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectacts',
            name='designer_engineer_decree',
            field=models.CharField(default=' ', max_length=100, verbose_name='Приказ проектировщика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blowdownact',
            name='purge_method',
            field=models.CharField(default='сетевой водой ХВС не менее 2-3 раз объема системы до "светлой воды"', max_length=150, verbose_name='Метод продувки'),
        ),
        migrations.AlterField(
            model_name='blowdownact',
            name='trassa',
            field=models.CharField(default='от отключающего устройства Д=     мм розлив холодного водоснабжения', max_length=150, verbose_name='Трасса'),
        ),
    ]
