# Generated by Django 2.1.7 on 2020-07-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0003_auto_20200331_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenactis',
            name='annex',
            field=models.CharField(blank=True, max_length=500, verbose_name='Приложения'),
        ),
        migrations.AddField(
            model_name='hiddenactis',
            name='docs',
            field=models.CharField(blank=True, default='исполнительная схема, сертификаты/свителельства', max_length=500, verbose_name='Предьявлены документы'),
        ),
    ]
