# Generated by Django 2.1.7 on 2022-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0004_auto_20200715_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacts',
            name='contractor_supervisor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Технадзор заказчика'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='contractor_supervisor_decree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Приказ технадзора заказчика'),
        ),
    ]
