# Generated by Django 2.1.7 on 2019-04-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0004_remove_objectacts_blow_down_act'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlowDownAct',
        ),
    ]
