# Generated by Django 2.1.7 on 2019-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0004_auto_20190617_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenactis',
            name='work_SNIP',
            field=models.CharField(blank=True, max_length=100, verbose_name='СНИП:'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='designer_engineer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Проектировщик'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='designer_engineer_decree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Приказ проектировщика'),
        ),
    ]
