# Generated by Django 4.0.5 on 2022-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0009_remove_objectacts_washing_purging_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectacts',
            name='h_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата Акта'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='is_hydraulic_testing_act',
            field=models.BooleanField(default=False, verbose_name='Гидравлика'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='is_sewer_testing_act',
            field=models.BooleanField(default=False, verbose_name='Испытание канализации'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='is_washing_disinfection_act',
            field=models.BooleanField(default=False, verbose_name='Промывка/дезинфекция'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='is_washing_purging_act',
            field=models.BooleanField(default=False, verbose_name='Промывка/продувка'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='s_t_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата Акта'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='w_d_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата Акта'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='w_d_disinfection_protocol_1',
            field=models.CharField(default='А0806/64 от 15.06.2022 г.', max_length=200, verbose_name='Анализ воды 1'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='w_d_disinfection_protocol_2',
            field=models.CharField(default='4465/2022 от 10.06.2022 г.', max_length=200, verbose_name='Анализ воды 2'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='w_p_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата Акта'),
        ),
    ]
