# Generated by Django 4.0.5 on 2022-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0011_objectacts_h_act_number_objectacts_s_t_act_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectacts',
            name='h_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='h_act_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='is_sewer_testing_act',
            field=models.BooleanField(default=False, verbose_name='Испыт. канализации'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='is_washing_disinfection_act',
            field=models.BooleanField(default=False, verbose_name='Дезинфекция'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='is_washing_purging_act',
            field=models.BooleanField(default=False, verbose_name='Продувка'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='s_t_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='s_t_act_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='w_d_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='w_d_act_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='w_p_act_date',
            field=models.CharField(default='"15" июня 2022 г.', max_length=50, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectacts',
            name='w_p_act_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
    ]
