# Generated by Django 4.0.6 on 2023-04-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0012_alter_objectacts_h_act_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='certificates/', verbose_name='Файл')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='hiddenactis',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='acts', to='hiddenactsbase.certificate', verbose_name='Сертификаты'),
        ),
    ]
