# Generated by Django 4.0.6 on 2024-06-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenactsbase', '0014_objectacts_service_engineer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-year', 'description'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AddField(
            model_name='objectacts',
            name='a_act_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='a_act_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='contract',
            field=models.CharField(blank=True, max_length=100, verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='objectacts',
            name='is_adjusting_heating_act',
            field=models.BooleanField(default=False, verbose_name='Балансировка'),
        ),
    ]
